name: money-keeper

on:
  push:
    paths:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [16.x]
        timezone: [UTC, Asia/Ho_Chi_Minh]
    steps:
      - name: Install modules
        uses: yarn/action-setup@v2
      - run: yarn run dev
