version: '3.8'
services:
  auth-service:
    build:
      context: ./packages/auth-service
    container_name: auth-service
    ports:
      - '3301:3301'
    environment:
      - NODE_ENV=production
      - PORT=3301

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
