name: money-keeper-ci/cd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-package:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm bootstrap
      - name: Run test all
        run: pnpm test
      - name: Run build api order
        run: pnpm build:api-order

  publish-package:
    name: Publish Package to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Check for changes in packages/shared
        id: check_changes
        run: |
          if git diff --exit-code HEAD^ HEAD -- packages/shared; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      - name: Publish if changes detected
        if: steps.check_changes.outputs.has_changes == 'true' && github.event_name == 'push' && !contains(github.event.head_commit.message, 'chore(release):')
        run: |
          # Set Git user info
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Authenticate with npm
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

          # Install PNPM
          npm install -g pnpm

          # Install dependencies, build interfaces, and bump version
          pnpm bootstrap
          pnpm build:interfaces
          pnpm bump-version

          git push --follow-tags origin main
            
          # Push changes and tags to main branch
          pnpm deploy:prod

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-package]
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, 'chore(release):') }}
    steps:
      - name: Deploy to Production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
