name: money-keeper-ci/cd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-package:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: userNode
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: yarn install
      - name: run build
        run: yarn run build

  publish-package:
    name: Publish Package
    needs: [build-package]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: redirect packages
        run: cd packages
      - name: Install Dependencies for packages
        run: yarn install
      - name: test
        run: ls
      - name: Run Build
        run: yarn run build
      - name: Set Git user info
        run: |
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config user.name "${{ secrets.GIT_USER_NAME }}"
      - name: Generate Changelog and Bump Version
        run: npx standard-version
      - name: Publish to npm
        run: npm publish --access public
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-package]
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
