name: money-keeper-ci/cd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-package:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: userNode
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: yarn install
      - name: run build
        run: yarn run build

  publish-package:
    name: Publish Package
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Set Git user info
        run: |
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config user.name "${{ secrets.GIT_USER_NAME }}"
      - name: Change to 'packages' directory and run commands
        run: |
          cd packages
          yarn install
          yarn run build
          yarn standard-version
          yarn publish --access public
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-package]
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
