name: money-keeper-backend

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: userNode
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies
        run: yarn install
      - name: run build
        run: yarn run build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Render
        run: https://api.render.com/deploy/srv-cj71tgs5kgrc73f7ekbg?key=aVRBEVEFfDE
